podTemplate(containers: [
    containerTemplate(
        name: 'nodejsbuild', 
        image: 'node:18-alpine', 
        command: 'sleep', 
        args: '30d')
  ]) {

    node(POD_LABEL) {
        parameters {
            string(defaultValue: 'samplebucketfortesting12345', description: 'Bucket to Store Buildfiles', name: 'bucket')
        }

        stages {
            git 'https://github.com/spring-projects/spring-petclinic.git'
            container('nodejsbuild') {
                stage('Build UI bundles') {
                    sh "cd simpleGoserver/ui && npm install && npm run build"
                    sh "zip build.zip ./simpleGoserver/ui/build/"
                    sh "aws s3 cp build.zip s3://${params.bucket}/postsapp/buildfiles/"
                }
            }
        }
    }
}
