podTemplate(containers: [
    containerTemplate(
        name: 'jnlp', 
        image: 'jenkins/inbound-agent:latest'
        ),
    containerTemplate(
        name: 'nodejsbuild', 
        image: 'node:18-alpine', 
        command: 'sleep', 
        args: '30d'),
    containerTemplate(
        name: 'awscli', 
        image: 'amazon/aws-cli:latest', 
        command: 'sleep', 
        args: '30d')
  ]) {
    node(POD_LABEL) {
        parameters {
            string(defaultValue: 'samplebucketfortesting12345', description: 'Bucket to Store Buildfiles', name: 'bucket')
        }

        stage('Checkout Git') {
            container('jnlp') {
                stage('git checkout') {
                    checkout scm
                }
            }
        }

        stage('Build UI') {
            container('nodejsbuild') {
                stage('Build UI bundles') {
                    sh "cd simpleGoserver/ui && npm install && npm run build"
                }
            }
        }

        stage('Tar Ball') {
            container('jnlp') {
                stage('Make a tar file') {
                    sh "cd simpleGoserver/ui && tar -cvf build.tar.gz ./build/"
                }
            }
        }

        stage('Upload to S3') {
            container('awscli') {
                stage('Upload to S3') {
                    sh "cd simpleGoserver/ui && aws s3 cp build.tar.gz s3://${params.bucket}/postsapp/buildfiles/"
                }
            }
        }
    }
}
