podTemplate(
    containers: [
        containerTemplate(
            name: 'jnlp', 
            image: 'jenkins/inbound-agent:latest'
            ),
        containerTemplate(
            name: 'gobuild', 
            image: 'golang:1.24', 
            command: 'sleep', 
            args: '30d'),
        containerTemplate(
            name: 'awscli', 
            image: 'amazon/aws-cli:latest', 
            command: 'sleep', 
            args: '30d')
    ], 
    serviceAccount: "go-server-account",
    nodeSelector: "kubernetes.io/arch:amd64",
  ) {
    node(POD_LABEL) {
        parameters {
            string(defaultValue: 'samplebucketfortesting12345', description: 'Bucket to Store Buildfiles', name: 'bucket')
        }

        stage('Checkout Git') {
            container('jnlp') {
                stage('git checkout') {
                    checkout scm
                    sh "git config --global --add safe.directory '*'"
                }
            }
        }

        stage('Build Web Server') {
            container('gobuild') {
                stage('Build go server') {
                    sh "cd simpleGoserver && go get github.com/coreos/go-oidc/v3/oidc golang.org/x/net/context golang.org/x/oauth2 github.com/alexedwards/scs/v2 github.com/go-sql-driver/mysql github.com/aws/aws-sdk-go-v2/config github.com/aws/aws-sdk-go-v2/service/ssm github.com/alexedwards/scs/mysqlstore github.com/prometheus/client_golang/prometheus && go build -buildvcs=false -v -o app"
                }
            }
        }

        stage('Upload to S3') {
            container('awscli') {
                stage('Upload to S3') {
                    sh "cd simpleGoserver && aws s3 cp app s3://${params.bucket}/postsapp/buildfiles/"
                }
            }
        }
    }
}
