pipeline {
    agent { node { label 'ec2slave' } } 

    parameters {
        string(defaultValue: 'ap-south-1', description: 'Region of ECR Repo', name: 'AwsRegion')
        string(description: 'Account of ECR Repo', name: 'ECRAccount')
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('BuildImage') {
            steps {
                sh "aws ecr get-login-password --region ${params.AwsRegion} | docker login --username AWS --password-stdin ${params.ECRAccount}.dkr.ecr.${params.AwsRegion}.amazonaws.com"
                sh "ls -l ; pwd"
                sh "cd simpleGoServer"
                sh "docker build -t simplegoserver ."
                sh "docker images"
                sh "docker tag simplegoserver ${params.ECRAccount}.dkr.ecr.${params.AwsRegion}.amazonaws.com/apprepo:latest"
                sh "docker push ${params.ECRAccount}.dkr.ecr.${params.AwsRegion}.amazonaws.com/apprepo:latest"
            }
        }

    }
}
