apiVersion: v1
kind: Config
clusters:
  - name: my-cluster
    cluster:
      server: https://kubeadmin.${domain} 
contexts:
  - name: my-context
    context:
      cluster: my-cluster
      user: my-user
      namespace: default # Optional, specify a default namespace if needed
current-context: my-context
users:
  - name: my-user
    user:
      tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token